name: Debug
on: pull_request
jobs:
    debug:
        runs-on: ubuntu-latest
        steps:
            - name: Check out the repository
              uses: actions/checkout@v4
            - name: Print github context
              run: echo "${CONTEXT}"
              env:
                CONTEXT: ${{ toJson(github.event.pull_request) }}