name: Literals
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${CONTEXT}"
              env:
                  CONTEXT: ${{ toJSON(github) }} # コンテキストのJSON文字列化
