name: Manual
on:
    workflow_dispatch: # 手動実行イベント
        inputs:
            name: # 入力パラメータ名
                type: string # データ型（文字列）
                default: Takaya # 入力パラメータのデフォルト値
                required: true # 入力パラメータの必須フラグ
                description: 名前 # 入力パラメータの概要
            title: # 入力パラメータ名
                type: choice # データ型（選択肢）
                options: ["さん", "様"] # 選択肢のリスト
                required: true # 入力パラメータの必須フラグ
                description: 敬称 # 入力パラメータの概要
jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - run: echo "${{ inputs.name }}" # 入力パラメータ「name」の参照
